name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Keychain
      id: setup-keychain
      uses: ./
    - name: Echo keychain name
      run: echo 'Keychain name is ${{ steps.setup-keychain.outputs.keychain-name }}'
    - name: Echo keychain password
      run: echo 'Keychain password is ${{ steps.setup-keychain.outputs.keychain-password }}'
